application/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView

from .views import SignUpView, logout_view

app_name = "accounts"

urlpatterns = [
    url(r'^signup/', SignUpView.as_view(), name='signup', ),
    url(r'^login/', LoginView.as_view(redirect_authenticated_user=True),name='login', ),
    url(r'^logout/', logout_view, name='logout'),
   
]

application/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('index.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^products/', include('products.urls')),


]

application/home/urls.py
from django.conf.urls import url


from .views import HomeView

app_name = "home"

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home', ),
 
 
]

application/index/urls.py
from django.conf.urls import url

from .views import indexView

app_name = "index"


urlpatterns = [
    url(r'^$', indexView.as_view(), name='index', ),
]

application/products/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'products'

urlpatterns = [
    url(r'^products/$', views.products_list, name='products_list'),
    url(r'^products/create$', views.products_create, name='product_create'),
    url(r'^products/(?P<id>\d+)/update$', views.product_update, name='product_update'),
    url(r'^products/(?P<id>\d+)/delete$', views.product_delete, name='product_delete'),
]

application/accounts/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    cep = models.CharField(verbose_name='CEP',  max_length=9,)
    address = models.CharField(max_length=30, verbose_name='Endereço', )
    number = models.PositiveIntegerField(default=0, verbose_name='Número', validators=[MaxValueValidator(9999)],)
    complement = models.CharField(max_length=20, verbose_name='Complemento', null=True, blank=True )
    neighborhood = models.CharField(max_length=20, verbose_name='Bairro', )
    city = models.CharField(max_length=20, verbose_name='Cidade', )
    uf = models.CharField( max_length=2, verbose_name='Unidade federativa', default='MG')
    email = models.EmailField(_('email address'), unique=True)
    username = None


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

application/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

application/index/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

application/products/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator



class Products(models.Model):
    name = models.CharField(max_length=30, verbose_name='Nome', )
    price = models.FloatField(verbose_name='preço', validators=[MinValueValidator(0.0), MaxValueValidator(99999999.0)])
    stock = models.PositiveIntegerField( verbose_name='Stock', validators=[MaxValueValidator(9999)],)
    def __str__(self):
        return "{}: ID: {}, ".format(self.name, self.id,)


        
    class Meta:
        verbose_name = 'produtos'
        ordering = ['name', '-price', '-stock']

application/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


from accounts.models import CustomUser


class CreationUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'email', 'password1', 'password2', 'cep', 'address', 'number', 'complement', 'neighborhood', 'city', 'uf' )
        

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email')

application/home/forms.py
from django.forms import ModelForm

application/products/forms.py
from django import forms
from .models import Products

class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = '__all__'
   

application/accounts/views.py
from django.http import HttpResponseRedirect

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views



from accounts.forms import CreationUserForm, LoginForm



class SignUpView(generic.CreateView):
    form_class = CreationUserForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'registration/signup.html'


class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('index:index')




def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse_lazy('index:index'))

application/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import JsonResponse
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from products.models import Products

# Create your views here.
   

class HomeView(TemplateView, LoginRequiredMixin):

    template_name = "home.html"


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(HomeView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the products
        context['productsCount'] = Products.objects.all().count()
        context['title'] = 'Home'

        return context

application/index/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic.base import TemplateView

# Create your views here.



class indexView(TemplateView):

    template_name = "index.html"

application/products/views.py
from django.shortcuts import render,get_object_or_404
from .models import Products
from .forms import ProductsForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

@login_required
def products_list(request):
	products = Products.objects.all()
	context = {
	'products': products, 'title':'Produtos'
	}
	return render(request, 'product_list.html',context)

@login_required
def save_all(request,form,template_name):
	data = dict()
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			data['form_is_valid'] = True
			products = Products.objects.all()
			data['product_list'] = render_to_string('product_list_2.html',{'products':products})
		else:
			data['form_is_valid'] = False
	context = {
	'form':form
	}
	data['html_form'] = render_to_string(template_name,context,request=request)
	return JsonResponse(data)

@login_required
def products_create(request):
	if request.method == 'POST':
		form = ProductsForm(request.POST)
	else:
		form = ProductsForm()
	return save_all(request,form,'product_create.html')

@login_required
def product_update(request,id):
	product = get_object_or_404(Products,id=id)
	if request.method == 'POST':
		form = ProductsForm(request.POST,instance=product)
	else:
		form = ProductsForm(instance=product)
	return save_all(request,form,'product_update.html')

@login_required
def product_delete(request,id):
	data = dict()
	product = get_object_or_404(Products,id=id)
	if request.method == "POST":
		product.delete()
		data['form_is_valid'] = True
		products = Products.objects.all()
		data['product_list'] = render_to_string('product_list_2.html',{'products':products})
	else:
		context = {'product':product}
		data['html_form'] = render_to_string('product_delete.html',context,request=request)

	return JsonResponse(data)

application/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Teste E-Soft</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
<!--===============================================================================================-->
</head>
{%block content%}
{%endblock%}

<!--===============================================================================================-->
<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
{% static 'js\jquery-3.1.1.min.js' %}
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

</body>
</html>

application/home/templates/home.html
{% extends 'home/base.html' %}
{%block content%}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>

      <div class="card w-50">
        <div class="card-body" style="text-align:center;">
          <p class="card-title">Produtos cadastrados</p>
          <h5 class="card-text">  {{productsCount}}</h5>
          <a href="{% url 'products:products_list' %}" class="btn btn-primary">Produtos</a>
        </div>
      </div>
      </div>
  {%endblock%}

application/index/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <title>Rogelio Rodriguez</title>


    

    

<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'pricing.css' %}" rel="stylesheet">
  <body>
    
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="{% url 'index:index' %}" class="d-flex align-items-center text-dark text-decoration-none">
        <span class="fs-4">Teste</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'index:index' %}">Home</a>
      {%if not user.is_authenticated %} 
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:login' %}">Login</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:signup' %}">Cadastrar</a>
      
      {%else%} 
      <a class="me-3 py-2 text-dark text-decoration-none" href="#">{{user}}</a>
      <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:logout' %}">Logout</a>

    {%endif%}
      </nav>
    </div>

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Rogelio Rodriguez</h1>
      <p class="fs-5 text-muted">Engenheiro em Informatica, treinado para realizar soluções e aplicações web, a fim de oferecer às empresas produtos à altura do mercado. Preparado para trabalho em equipe e com experiência em trabalho remoto e cumprimento de objetivos.</p>
    </div>
  </header>

  <main>
    <div class="info pricing-header p-3 pb-md-4 mx-auto text-center"'>
    <h5 class="display-4 fw-normal .text-center">Informações Básicas </h5>
      
        <p class="fs-5 text-muted">Email: Rogelio23rodriguez@gmail.com </p>
        <p class="fs-5 text-muted">Linkedin: Linkedin.com/in/rogelio-rod</p>
        <p class="fs-5 text-muted">GitHub: Github.com/rogeliorodriguez27</p>
        <p class="fs-5 text-muted">Gitlab: Gitlab.com/rogeliorodriguez27</p>
      
    </div>
    

    
  </main>

  <footer class=" border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small id='year' class="d-block mb-3 text-muted"></small>

      </div>
     
  </footer>
</div>


    
  

</body>
<script>
  let yearVariable = document.getElementById('year');
  let date =  new Date().getFullYear();
  let text = document.createTextNode('Rogelio Rodriguez ' + date);
  yearVariable.appendChild(text);


</script>



</html>

application/products/templates/product_create.html
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'products:product_create' %}" class="create-form">
	{% csrf_token %}
		<div class="modal-header">
		<h5 class="modal-title" >Criar Produto</h5>
		</div>
		<div class="modal-body">
		{{form|crispy}}
		</div>
		<div class="modal-footer">
		<button type="submit" class="btn btn-primary">Criar Produto</button>
		</div>
</form>

application/products/templates/product_delete.html
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'products:product_delete' product.id %}" class="delete-form">
	{% csrf_token %}
		<div class="modal-header">
		<h5 class="modal-title" >Excluir Produto</h5>
		</div>
		<div class="modal-body">
		<p class="lead"> Seguro que deseja excluir <strong>{{product.name}}</strong></p>
		</div>
		<div class="modal-footer">
		<button type="submit" class="btn btn-danger">Excluir</button>
		</div>
</form>

application/products/templates/product_list.html
{% extends 'home/base.html' %}

{% block content %}
  <h1 class="page-header">Produtos</h1>
  <button class="btn btn-primary show-form" data-url="{% url 'products:product_create' %}">
  <span class="glyphicon glyphicon-plus"></span>
  Cadastrar
  </button>
  <table class="table" id="product-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Preço</th>
        <th>Estoque</th>
        </tr>
    </thead>
    <tbody>
      {% include "product_list_2.html" %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-product">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
  </div>
{% endblock %}

application/products/templates/product_list_2.html
{% for product in products %}
{% if product.stock < 1 %}  
<tr class="table-danger">
  {% else %}
  <tr>
  {% endif %}
  <td>{{ product.id }}</td>
  <td>{{ product.name }}</td>
  <td>{{ product.price }}</td>
  <td>{{ product.stock }}</td>
  
    
    <td>  
      <button class="btn btn-warning show-form-update" data-url="{% url 'products:product_update' product.id %}">
      <span class="glyphicon glyphicon-pencil"></span>
      Editar 
      </button>
    </td>
    <td>  
      <button class="btn btn-danger show-form-delete" data-url="{% url 'products:product_delete' product.id %}">
      <span class="glyphicon glyphicon-trash"></span>
      Excluir 
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="7" class="text-center bg-warning">0 Registros</td>
  </tr>
{% endfor %}

application/products/templates/product_update.html
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'products:product_update' form.instance.id %}" class="update-form">
	{% csrf_token %}
		<div class="modal-header">
		<h5 class="modal-title" >Editar Produto</h5>
		</div>
		<div class="modal-body">
		{{form|crispy}}
		</div>
		<div class="modal-footer">
		<button type="submit" class="btn btn-primary">Editar Produto</button>
		</div>
</form>

application/templates/home/base.html
{%load static%}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{{title}}</title>

    <link
      href="{% static 'bootstrap.min.css' %}"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />

    <!-- Favicons -->

    <meta name="theme-color" content="#712cf9" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, 0.1);
        border: solid rgba(0, 0, 0, 0.15);
        border-width: 1px 0;
        box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
          inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -0.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard.css' %}" rel="stylesheet" />
    <link
      rel="preconnect"
      href="https://fonts.googleapis.com/"
      crossorigin="true"
    />
    <link rel="preconnect" href="https://fonts.gstatic.com/" />
    <link rel="stylesheet" href="{% static 'css2' %}" />
  </head>
  <body>
    <header
      class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow"
    >
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#"
        >Teste</a
      >
      <button
        class="navbar-toggler position-absolute d-md-none collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu"
        aria-controls="sidebarMenu"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-nav">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#"
          >{{user}}</a
        >
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav
          id="sidebarMenu"
          class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
        >
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a
                  class="nav-link"
                  aria-current="page"
                  href="{% url 'home:home' %}"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="feather feather-home align-text-bottom"
                    aria-hidden="true"
                  >
                    <path
                      d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
                    ></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                  </svg>
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:products_list' %}">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="feather feather-shopping-cart align-text-bottom"
                    aria-hidden="true"
                  >
                    <circle cx="9" cy="21" r="1"></circle>
                    <circle cx="20" cy="21" r="1"></circle>
                    <path
                      d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"
                    ></path>
                  </svg>
                  Produtos
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="feather feather-users align-text-bottom"
                    aria-hidden="true"
                  >
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                    <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                  </svg>
                  Salir
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="container">
            {% block content %}
            {% endblock %}
          </div>
          <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>  
          <script src="{% static 'bootstrap\js\bootstrap.min.js' %}"></script>
          <script src="{% static 'js/plugin.js' %}"></script>
          {% block javascript %}
          {% endblock %}
      

        </main>
      </div>
    </div>

   
    <script src="{% static 'bootstrap\js\bootstrap.bundle.min.js' %}"></script>
  </body>

</html>